DB-4552: Add nonce verification to preview site form.
pantheon-systems/wp-decoupled-preview pull request #10
Opened 2022-11-30 13:19 UTC by abhisekmazumdar

2022-11-30 15:52 UTC, jazzsequence submitted a review, later dismissed
This looks right to me. Have not tested.

2022-12-01 19:43 UTC, backlineint requested changes
Based on local testing, I'm not sure these changes are having the desired effect. The nonces here don't seem to be enforced.

Unrelated to this code (I think) the form does use a hidden input with a nonce for verification - it isn't possible to save or delete a preview site unless that nonce is valid.

Those actions are the most important things we need to protect from. Would you agree that this covers us? Is there anything else we need to protect from here?

2022-12-01 19:43 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +							$href = 'options-general.php?page=delete_preview_site&delete=' . $edit_id . '&nonce=' . wp_create_nonce( 'delete_' . $edit_id );
From my local testing, I'm not confident that the nonce injected here is having any effect. If I remove the nonce from the URL, I can still delete the preview site.

The form itself has a hidden input for the nonce:

`<input type="hidden" id="_wpnonce" name="_wpnonce" value="4c09412c68">`

If I change the value, deleting the preview site will fail.  Maybe this is something we get for free from the WordPress form? Or maybe I'm missing something here.

2022-12-01 19:43 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
From my local testing, I'm not confident that the nonce injected here is having any effect. If I remove the nonce from the URL, I can still see the edit form.

2022-12-02 20:02 UTC, jazzsequence commented on src/class-decoupled-preview-settings.php
> +							$href = 'options-general.php?page=delete_preview_site&delete=' . $edit_id . '&nonce=' . wp_create_nonce( 'delete_' . $edit_id );
@backlineint Where is the code being run? There are a lot of places in the WordPress admin that already add nonces for things (like form submission on settings pages or anything that hooks into default page editing/deleting functions), so it could be that specifically adding a nonce is unnecessary. Worth noting too that typically the nonce would be created first (e.g. `$nonce = wp_create_nonce( 'yadda_yadda' )`) or added via a nonce field and then passed into the URL or form input rather than creating it on the fly.

https://developer.wordpress.org/themes/theme-security/using-nonces/

2022-12-02 20:08 UTC, jazzsequence commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
My expectation would be that there would be something on the page that did something like `$nonce = get_query_var( 'nonce' )` (assuming the `nonce` query variable was added via `add_query_arg`) and then checked the validity of the nonce (`wp_verify_nonce( $nonce, 'yadda_yadda' )`) before doing whatever the nonce is trying to protect against.

http://developer.wordpress.org/reference/functions/get_query_var/
https://developer.wordpress.org/reference/functions/add_query_arg/

2022-12-05 10:42 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +							$href = 'options-general.php?page=delete_preview_site&delete=' . $edit_id . '&nonce=' . wp_create_nonce( 'delete_' . $edit_id );
This is a form for creating/managing the custom Decoupled Preview we are creating as options.
After activating the Plugin it should be accessible on /wp/wp-admin/options-general.php?page=preview_sites`

2022-12-05 14:42 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
Not sure why but `get_query_var` is not working in our case. I tried also with `add_filter( 'query_vars', 'add_custom_query_var' );` but `get_query_var` doesn't gave me anything return. 
So in the new commit you might see I'm using `$_REQUEST`.

2022-12-05 16:19 UTC, jazzsequence commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
In my experience, if a query variable wasn't added using `add_query_arg`, I don't think you can pull it using `get_query_var`. The query param might be there, but WordPress doesn't know about it. It's generally considered best practice to avoid using superglobals like `$_REQUEST`.

2022-12-05 16:21 UTC, jazzsequence commented on src/class-decoupled-preview-settings.php
> +							$href = 'options-general.php?page=delete_preview_site&delete=' . $edit_id . '&nonce=' . wp_create_nonce( 'delete_' . $edit_id );
If you're adding options through the WordPress settings API, you shouldn't need to add your own nonces as @backlineint has pointed out.

2022-12-06 12:21 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +							$href = 'options-general.php?page=delete_preview_site&delete=' . $edit_id . '&nonce=' . wp_create_nonce( 'delete_' . $edit_id );
Ok I removed it form the edit part. Also yes verified that WordPress settings API adds a nonces and its been validated.
Thanks @jazzsequence @backlineint for the inputs.

2022-12-07 15:27 UTC, backlineint requested changes

2022-12-07 15:27 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +									'nonce'  => wp_create_nonce( 'delete' . $edit_id ),
I'm still not confident that this nonce is being used.

If I copy the link from the preview button, remove the nonce param, and then load that link in a new tab, the preview site is still deleted.

2022-12-07 15:27 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +		public function get_action_id( string $action ) {
I should have caught this on previous review, but we need to make sure that the return values here are sanitized.

2022-12-07 15:55 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
Also, running the WordPress coding standards tool gives really good feedback on where nonces are missing and/or where variables need to be sanitized.

2022-12-07 16:17 UTC, jazzsequence commented on src/class-decoupled-preview-settings.php
> +							$listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=add_preview_site&edit={$id}&nonce={$nonce}'>Edit</a>";
Link: https://github.com/WordPress/WordPress-Coding-Standards

2023-01-03 12:42 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +									'nonce'  => wp_create_nonce( 'delete' . $edit_id ),
Yes I noticed that and made some changes to it. Hope it works now.

2023-01-09 16:10 UTC, backlineint requested changes

2023-01-09 16:10 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +			$edit_id = $this->request['edit'];
If we're going to use the $_REQUEST superglobal, we need to sanitize the value before using it. I'd suggest using php's filter_input or filter_input_array.

2023-01-09 16:10 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +						'nonce' => wp_create_nonce( 'edit' . $edit_id ),
I still don't think this nonce is having any impact. If I change that name of the param here it still works. The hidden form nonce that WordPress adds by default still protects us here, so I think this can be removed.

2023-01-11 10:14 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +						'nonce' => wp_create_nonce( 'edit' . $edit_id ),
That would be my miss. I was suppose to remove it.

2023-01-11 10:15 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +			$edit_id = $this->request['edit'];
Thanks for the suggesting using `filter_input` replaced all the use of direct use of request with `filter_input`.

2023-01-13 13:52 UTC, backlineint requested changes
Not exactly sure why, but this commit introduced a regression with editing preview sites. Rather than editing the existing site, a new preview site is created with the edits and the existing one is left as is.

2023-01-17 23:38 UTC, backlineint commented on src/class-decoupled-preview-settings.php
> +            }
The indentation is off here. We have a follow up task for code standards so we can fix that then.

Also on the line below the lingering ?> reads oddly. Not familiar enough, but seems like this would violate WP coding standards.

2023-01-17 23:38 UTC, backlineint approved these changes

2023-01-17 23:39 UTC, merged