DB-3888: Create settings page for Preview config.
pantheon-systems/wp-decoupled-preview pull request #2
Opened 2022-09-16 13:39 UTC by abhisekmazumdar

2022-09-29 15:25 UTC, backlineint requested changes

2022-09-29 15:25 UTC, backlineint commented on wp-decoupled-preview.php
> +    add_options_page( 'Create Preview Site', 'Create Preview Site', 'manage_options', 'wp_decoupled_preview_create', 'wp_decoupled_preview_create_html' );
Is there any way that this page could be enabled, but not included in the menu? Long term I think we'll just want to access this through the preview site configuration.

2022-09-29 15:25 UTC, backlineint commented on wp-decoupled-preview.php
> +    add_options_page( 'Create Preview Site', 'Create Preview Site', 'manage_options', 'wp_decoupled_preview_create', 'wp_decoupled_preview_create_html' );
I'd expect there to be an 'add new preview site' button, along with a list of existing preview sites that can be edited.

2022-09-29 15:25 UTC, backlineint commented on wp-decoupled-preview.php
> +    $listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=wp_decoupled_preview_create'>Edit</a";
As I know you're aware, this currently assumes that there is only one preview site value. It is possible to store an array in a single setting: https://stackoverflow.com/questions/70010438/wordpress-plugin-multiple-values-against-same-setting 

Looking at the row that is created in the wp_options table, the stored value is essentially just serialized json. For another settings example that has multiple values, take a look at `rewrite_rules` I don't think that is directly exposed in the UI, so that will only give you an example of how the data can be stored.

I did find this example post outlining how to create an options form with multiple values: https://web4pro.net/blog-news/option-fields-with-multiple-values/ Probably not exactly the same thing we want here (I don't think we'll need the JS for updating dynamically - navigating to the add/edit preview site form should be fine), but hopefully there are some things that apply.

2022-09-29 15:25 UTC, backlineint commented on wp-decoupled-preview.php
> +    register_setting('preview_configurations', 'preview');
It seems like maybe the arguments are reversed here and/or should be renamed.

`register_setting( $option_group, $option_name, $args )`

I think the option group should be the name of the plugin and the option name should be something like `preview_sites`

2022-09-29 15:25 UTC, backlineint commented on wp-decoupled-preview.php
> +    add_options_page( 'Preview Site Configuration', 'Preview Site Configuration', 'manage_options', 'wp_decoupled_preview_list', 'wp_decoupled_preview_list_html' );
The second arg of Menu Title seems a little redundant this this is already displayed in the settings section. Maybe something like 'Preview Sites'?

2022-10-04 12:48 UTC, abhisekmazumdar commented on wp-decoupled-preview.php
> +    add_options_page( 'Create Preview Site', 'Create Preview Site', 'manage_options', 'wp_decoupled_preview_create', 'wp_decoupled_preview_create_html' );
Yes we can just create option page and not add it to menu.

2022-10-10 13:19 UTC, abhisekmazumdar commented on wp-decoupled-preview.php
> +    add_options_page( 'Create Preview Site', 'Create Preview Site', 'manage_options', 'wp_decoupled_preview_create', 'wp_decoupled_preview_create_html' );
I was hoping this was possible. But yet didn't found any ways.

2022-10-10 13:20 UTC, abhisekmazumdar commented on wp-decoupled-preview.php
> +    $listing_data['edit'] = "<a href='/wp/wp-admin/options-general.php?page=wp_decoupled_preview_create'>Edit</a";
Thanks for the inputs this helped

2022-10-10 13:23 UTC, abhisekmazumdar commented
@backlineint There is one knows issue with this PR. I'm trying to find why this is happening but didn't had any luck yet.

When trying to add first preview config in the site the data won't get saved. So add another config then the data get saved from the 2nd configs.

2022-10-10 17:54 UTC, backlineint commented on wp-decoupled-preview.php
> +    add_options_page( 'Create Preview Site', 'Create Preview Site', 'manage_options', 'wp_decoupled_preview_create', 'wp_decoupled_preview_create_html' );
Would something like this help here? https://stackoverflow.com/a/11820396

2022-10-10 19:08 UTC, backlineint requested changes
A couple of other things I didn't mention inline:

* For cases where no preview sites have been added, there probably should be an `add preview site` button on the decoupled preview settings page.
* I noticed that the edit links for each preview site are broken. It might make sense to break that one out into an additional ticket since this one has been a larger effort than expected.

2022-10-11 06:47 UTC, abhisekmazumdar commented on src/settings.php
> +			echo 'These settings do things for the WP Plugin Template.';
Aah!! Need to update the text to something relevant. Thanks for pointing this out.

2022-10-12 22:31 UTC, backlineint commented
> Abhisek: I got a solution by creating a default value when activating the plugin.

@abhisekmazumdar Here's what I'm seeing testing the current branch. When creating my first preview site, the site does not show up in the list on the preview sites settings page. When creating my second preview site, it does display, but the first site does not. Adding a third site results in seeing the second and third sites in the table, and so on. Basically the first site seems to be deleted.

What I'm seeing in the database may provide some clues. After creating the first site the result is:

```
| 454 | preview_sites | a:1:{s:7:"preview";a:1:{i:1;a:1:{s:7:"preview";a:1:{i:1;a:4:{s:5:"label";s:18:"First Preview Site";s:3:"url";s:16:"http://yahoo.com";s:13:"secret_string";s:6:"dhdjhs";s:12:"preview_type";s:7:"Next.js";}}}}} | yes |
```

After creating the second site I see:

```
| 454 | preview_sites | a:1:{s:7:"preview";a:1:{i:0;a:5:{s:5:"label";s:19:"Second Preview Site";s:3:"url";s:17:"http://mysite.com";s:13:"secret_string";s:5:"hdjdj";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Post";}}} | yes |
```

Hard to tell the difference, but when comparing the two what gets stored for the first site seems to have too many closing curly braces somehow. This seems to result in the data for the first site being thrown out.

For completeness, here is what is stored after a third preview site is added:

```
| 454 | preview_sites | a:1:{s:7:"preview";a:2:{i:0;a:5:{s:5:"label";s:19:"Second Preview Site";s:3:"url";s:17:"http://mysite.com";s:13:"secret_string";s:5:"hdjdj";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Post";}i:1;a:5:{s:5:"label";s:18:"Third Preview Site";s:3:"url";s:17:"http://yahoo.com2";s:13:"secret_string";s:4:"1234";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Page";}}} | yes |
```

Both sites are combined into a single row.

2022-10-12 22:34 UTC, backlineint requested changes
Added a comment in the conversation tab about what I'm seeing when testing this (the first preview site ends up being discarded) and what I think might be causing that.

Also, here are a couple of other small things I noticed:
* Could we change the title in the settings menu from 'Preview Site' to 'Preview Sites'?
* When a preview site is saved, rather than redirecting to an empty form, could we redirect to the main Preview Site settings page that contains the list of preview sites.

2022-10-13 11:18 UTC, abhisekmazumdar commented
> > Abhisek: I got a solution by creating a default value when activating the plugin.
> 
> @abhisekmazumdar Here's what I'm seeing testing the current branch. When creating my first preview site, the site does not show up in the list on the preview sites settings page. When creating my second preview site, it does display, but the first site does not. Adding a third site results in seeing the second and third sites in the table, and so on. Basically the first site seems to be deleted.
> 
> What I'm seeing in the database may provide some clues. After creating the first site the result is:
> 
> ```
> | 454 | preview_sites | a:1:{s:7:"preview";a:1:{i:1;a:1:{s:7:"preview";a:1:{i:1;a:4:{s:5:"label";s:18:"First Preview Site";s:3:"url";s:16:"http://yahoo.com";s:13:"secret_string";s:6:"dhdjhs";s:12:"preview_type";s:7:"Next.js";}}}}} | yes |
> ```
> 
> After creating the second site I see:
> 
> ```
> | 454 | preview_sites | a:1:{s:7:"preview";a:1:{i:0;a:5:{s:5:"label";s:19:"Second Preview Site";s:3:"url";s:17:"http://mysite.com";s:13:"secret_string";s:5:"hdjdj";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Post";}}} | yes |
> ```
> 
> Hard to tell the difference, but when comparing the two what gets stored for the first site seems to have too many closing curly braces somehow. This seems to result in the data for the first site being thrown out.
> 
> For completeness, here is what is stored after a third preview site is added:
> 
> ```
> | 454 | preview_sites | a:1:{s:7:"preview";a:2:{i:0;a:5:{s:5:"label";s:19:"Second Preview Site";s:3:"url";s:17:"http://mysite.com";s:13:"secret_string";s:5:"hdjdj";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Post";}i:1;a:5:{s:5:"label";s:18:"Third Preview Site";s:3:"url";s:17:"http://yahoo.com2";s:13:"secret_string";s:4:"1234";s:12:"preview_type";s:7:"Next.js";s:12:"content_type";s:4:"Page";}}} | yes |
> ```
> 
> Both sites are combined into a single row.

If the plugin is deactivated and then activated then I feel this shouldn't had happened. I tried with a fresh setup didn't face this issue.

2022-10-13 14:21 UTC, backlineint commented
> If the plugin is deactivated and then activated then I feel this shouldn't had happened. I tried with a fresh setup didn't face this issue.

You're right - I'm no longer able to duplicate this.

@abhisekmazumdar I did run into a smaller bug re-testing this.
* Create a new preview site and check both post and page content types.
* View the preview site list.
* Note that only the Page content type is saved.

This can be worked around by unchecking both content types, but I expect this would end up being confusing to users.

2022-10-14 08:01 UTC, abhisekmazumdar commented
> > If the plugin is deactivated and then activated then I feel this shouldn't had happened. I tried with a fresh setup didn't face this issue.
> 
> You're right - I'm no longer able to duplicate this.
> 
> @abhisekmazumdar I did run into a smaller bug re-testing this.
> 
> * Create a new preview site and check both post and page content types.
> * View the preview site list.
> * Note that only the Page content type is saved.
> 
> This can be worked around by unchecking both content types, but I expect this would end up being confusing to users.

Yes I was aware of issue hence added a new commit for this to be fixed

2022-10-17 14:18 UTC, backlineint requested changes
Everything is functioning great here. Thanks for sticking with this one :)

Requested a few minor changes inline - mostly language tweaks and typos. I also noticed that compared to files elsewhere in the codebase, the formatting doesn't seem consistent. The indentation appears to be too large, and is not always consistent. Could you update the formatting here?

With those changes this should be ready to merge.

2022-10-17 14:18 UTC, backlineint commented on src/settings.php
> +			echo 'Create or Edit Decoupled Preview for the Front-End Site';
Please change to 'Create or Edit Preview Site'

2022-10-17 14:18 UTC, backlineint commented on src/settings.php
> +		    echo "<br>[Required] Preview type for the frontend.";
'frontend' should be 'front-end'

2022-10-17 14:18 UTC, backlineint commented on src/settings.php
> +                        <span style="padding-left: 6.5rem"><a href="options-general.php?page=preview_sites" class="button">View all Preview Sites Config</a></span>
Since the equivalent sidebar menu item should be visible, I think this is redundant. Could you remove this button?

2022-10-17 14:18 UTC, backlineint commented on src/settings.php
> +                    <span style="font-weight: bold; font-size: 1.5rem">Previews Site Configuration</span>
'Previews' should be 'Preview'

2022-10-19 13:57 UTC, abhisekmazumdar commented on src/class-decoupled-preview-settings.php
> +			// TODO: Processing form data with nonce verification.
Should we create a new ticket for this?
I tried fixing this part of this ticket but looks like there more effort in this.

2022-10-19 22:38 UTC, backlineint approved these changes

2022-10-19 22:38 UTC, merged