Updates to readme.txt
pantheon-systems/wp-decoupled-preview pull request #21
Opened 2023-03-21 00:46 UTC by backlineint

Fleshed out the readme prior to publishing on wordpress.org

2023-03-21 00:55 UTC, scottbuscemi commented on readme.txt
> +supports NextJS. It was developed in support of [Pantheon's Next WordPress Starter](https://github.com/pantheon-systems/next-wordpress-starter), but can be applied to other
@backlineint Curious why this block of text is broken into multiple lines?

2023-03-21 10:28 UTC, abhisekmazumdar commented on readme.txt
> +supports NextJS. It was developed in support of [Pantheon's Next WordPress Starter](https://github.com/pantheon-systems/next-wordpress-starter), but can be applied to other
I guess the IDE settings to follow WordPress Coding Standards might have created this break.
Lets make it in one line.

2023-03-21 10:29 UTC, abhisekmazumdar commented
Other then the inline mentioned comment everything else LGTM.

2023-03-21 14:51 UTC, jazzsequence requested changes
There's a couple minor formatting issues relating to WP.org's pseudo-markdown quirks and some suggestions that would help WP.org users.

2023-03-21 14:51 UTC, jazzsequence commented on readme.txt
> +## Features
I think `##` will evaluate to `==` in WordPress pseudo-markdown, which makes this the same level as the Description and will effectively shorten the "long" description to a single line. I think this should be dropped down to `===`.

```suggestion
=== Features ===
```

2023-03-21 14:51 UTC, jazzsequence commented on readme.txt
> +## Configuration
This one is probably good to be an H2, but should conform to the WP pseudo-markdown syntax since we're using that elsewhere.

```suggestion
== Configuration ==
```

2023-03-21 14:51 UTC, jazzsequence commented on readme.txt
> +
If there is public-facing documentation about configuring this, it should be linked here. I'm not sure -- on Pantheon or off -- that everyone would understand the purpose of the Secret and how it would be used.

2023-03-21 14:59 UTC, jazzsequence commented on readme.txt
> +Stable tag: 0.2.1
Also: [Don't fear the 1.0](https://pantheon.io/blog/dont-fear-1-0-rational-project-management-libraries-using-semver)

2023-03-24 20:25 UTC, backlineint commented on readme.txt
> +supports NextJS. It was developed in support of [Pantheon's Next WordPress Starter](https://github.com/pantheon-systems/next-wordpress-starter), but can be applied to other
I'm in the habit of following a max line length for files, including things like markdown. And yeah, VS code usually does this automatically for me. I guess this shouldn't apply to a .txt file since it won't be rendered as markup. I'll update.

2023-03-24 20:33 UTC, backlineint commented on readme.txt
> +## Features
Thanks for catching this. I miss my markdown :)

2023-03-24 21:18 UTC, jazzsequence approved these changes
G2G :shipit:

2023-03-24 21:22 UTC, merged