DB-3191: Add Decoupled Preview menu link to admin_bar_menu.
pantheon-systems/wp-decoupled-preview pull request #3
Opened 2022-10-04 08:55 UTC by abhisekmazumdar

2022-10-05 21:02 UTC, backlineint requested changes
On this branch I'm currently unable to activate the plugin. When I activate it, I see the following message:

The plugin generated 1 character of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

And then I don't see the entry under settings in the menu. 

Provided some other comments based just on reading the code - making some assumptions without being able to test this hands on.

2022-10-05 21:02 UTC, backlineint commented on wp-decoupled-preview.php
> +        $admin_bar->add_menu([
This looks like it will add a static link for 'decoupled preview'. Per the acceptance criteria this should instead be the name of the configured preview site.

2022-10-06 11:15 UTC, abhisekmazumdar commented on wp-decoupled-preview.php
> +    if (( $pagenow == 'post.php' ) || (get_post_type() == 'post') || (get_post_type() == 'page')) {
So as the form work in not yet WIP([PR](https://github.com/pantheon-systems/wp-decoupled-preview/pull/2)). We can't set or check the values here yet.
I will take care of this on the [DB-3888](https://getpantheon.atlassian.net/browse/DB-3888)

2022-10-06 11:32 UTC, abhisekmazumdar commented
Looks like these changes are more depended on [DB-3888](https://getpantheon.atlassian.net/browse/DB-3888).
I will start on this after DB-3888 has gone for review.

2022-10-13 11:09 UTC, abhisekmazumdar commented on src/settings.php
> +            // TODO: If no options are set in $site['content_type'] then its considered enabled for all the content pages.
An note to myself:
Before sending it to review will need to work on this case. Right now there is an issue in DB-3888 which is blocking this.

2022-10-14 08:04 UTC, abhisekmazumdar commented on src/settings.php
> +        protected function getPreviewSite() {
Need to remove this helper function as it part of [DB-3888](https://github.com/pantheon-systems/wp-decoupled-preview/pull/2/commits/a8913b9b655c845868d3edc95a6fc6476509a97f#diff-f233643e5bfb01ce9ce3a4c020dc5a772a4448519bcf97b565fc64daa7eade56R237) now

2022-10-24 15:23 UTC, backlineint requested changes
It took me a while to find where the preview menu was. I'd like to see us move this into the post settings section where the existing preview lives. At a high level, I'd try something like this:

* Update the existing preview menu so it is hidden by default.
* Add a js directory to the plugin with a new js file.
* Enqueue this script only if the preview menu is being added.

And here is a quick POC for the script itself. Some of the styling needs to be refined, but it is a start.

```js
window.addEventListener("load", () => {
  // Hide default preview. We'll reconsider this in the future, but for now reduces confusion.
  document
    .querySelector(".block-editor-post-preview__dropdown")
    .classList.add("hidden");

  // Select the decoupled preview menu from the admin bar.
  const decoupledPreviewMenu = document.querySelector(
    "#wp-admin-bar-decoupled-preview"
  );

  // Hide submenu items by default.
  const previewSubmenu = decoupledPreviewMenu.querySelector(".ab-sub-wrapper");
  previewSubmenu.classList.add("hidden");

  // Add event listener to toggle submenu items.
  decoupledPreviewMenu.addEventListener("click", (e) => {
    previewSubmenu.classList.toggle("hidden");
  });

  // Add preview menu to post header settings
  const settingsSection = document.querySelector(".edit-post-header__settings");
  settingsSection.appendChild(decoupledPreviewMenu);
});

```

2022-10-28 10:22 UTC, abhisekmazumdar commented on wp-decoupled-preview.php
> +	$preview_helper      = new Decoupled_Preview_Settings();
Added this fix. I realised this while working on DB-4072.

2022-10-28 16:29 UTC, merged